//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Services_Cliente.MatematicasSvc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MatematicasSvc.IMatematicas")]
    public interface IMatematicas {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatematicas/sumar", ReplyAction="http://tempuri.org/IMatematicas/sumarResponse")]
        int sumar(int num1, int num2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatematicas/Restar", ReplyAction="http://tempuri.org/IMatematicas/RestarResponse")]
        int Restar(int num1, int num2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMatematicasChannel : Web_Services_Cliente.MatematicasSvc.IMatematicas, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MatematicasClient : System.ServiceModel.ClientBase<Web_Services_Cliente.MatematicasSvc.IMatematicas>, Web_Services_Cliente.MatematicasSvc.IMatematicas {
        
        public MatematicasClient() {
        }
        
        public MatematicasClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MatematicasClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MatematicasClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MatematicasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int sumar(int num1, int num2) {
            return base.Channel.sumar(num1, num2);
        }
        
        public int Restar(int num1, int num2) {
            return base.Channel.Restar(num1, num2);
        }
    }
}
