//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Bibliotecas.DALC
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class BibliotecasEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto BibliotecasEntities usando la cadena de conexión encontrada en la sección 'BibliotecasEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public BibliotecasEntities() : base("name=BibliotecasEntities", "BibliotecasEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto BibliotecasEntities.
        /// </summary>
        public BibliotecasEntities(string connectionString) : base(connectionString, "BibliotecasEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto BibliotecasEntities.
        /// </summary>
        public BibliotecasEntities(EntityConnection connection) : base(connection, "BibliotecasEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Biblioteca> Biblioteca
        {
            get
            {
                if ((_Biblioteca == null))
                {
                    _Biblioteca = base.CreateObjectSet<Biblioteca>("Biblioteca");
                }
                return _Biblioteca;
            }
        }
        private ObjectSet<Biblioteca> _Biblioteca;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Biblioteca. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToBiblioteca(Biblioteca biblioteca)
        {
            base.AddObject("Biblioteca", biblioteca);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BibliotecasModel", Name="Biblioteca")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Biblioteca : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Biblioteca.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad Id.</param>
        /// <param name="nombre">Valor inicial de la propiedad Nombre.</param>
        /// <param name="publica">Valor inicial de la propiedad Publica.</param>
        /// <param name="inauguracion">Valor inicial de la propiedad Inauguracion.</param>
        /// <param name="libros">Valor inicial de la propiedad Libros.</param>
        public static Biblioteca CreateBiblioteca(global::System.Int32 id, global::System.String nombre, global::System.Boolean publica, global::System.DateTime inauguracion, global::System.Int32 libros)
        {
            Biblioteca biblioteca = new Biblioteca();
            biblioteca.Id = id;
            biblioteca.Nombre = nombre;
            biblioteca.Publica = publica;
            biblioteca.Inauguracion = inauguracion;
            biblioteca.Libros = libros;
            return biblioteca;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Publica
        {
            get
            {
                return _Publica;
            }
            set
            {
                OnPublicaChanging(value);
                ReportPropertyChanging("Publica");
                _Publica = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Publica");
                OnPublicaChanged();
            }
        }
        private global::System.Boolean _Publica;
        partial void OnPublicaChanging(global::System.Boolean value);
        partial void OnPublicaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Inauguracion
        {
            get
            {
                return _Inauguracion;
            }
            set
            {
                OnInauguracionChanging(value);
                ReportPropertyChanging("Inauguracion");
                _Inauguracion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Inauguracion");
                OnInauguracionChanged();
            }
        }
        private global::System.DateTime _Inauguracion;
        partial void OnInauguracionChanging(global::System.DateTime value);
        partial void OnInauguracionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Libros
        {
            get
            {
                return _Libros;
            }
            set
            {
                OnLibrosChanging(value);
                ReportPropertyChanging("Libros");
                _Libros = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Libros");
                OnLibrosChanged();
            }
        }
        private global::System.Int32 _Libros;
        partial void OnLibrosChanging(global::System.Int32 value);
        partial void OnLibrosChanged();

        #endregion

    
    }

    #endregion

    
}
